#!/bin/bash
dir='/home/oliver/media/screenshots'
output='/home/oliver/media/screenshots/%Y-%m-%d-%T-screenshot.png'

case "$1" in
  "select") scrot "$output" --select --line mode=edge || exit ;;
  "window") scrot "$output" --focused --border || exit ;;
  *) scrot "$output" || exit ;;
esac

notify-send -a screenshot "screenshot taken" "See $dir"
